export interface LoggedInUser {
  "pk": number,
  "username": string,
  "is_verified": boolean,
  "profile_pic_url": string
  "full_name": string,
  "pk_id": string,
  "is_private": boolean,
  "account_badges": Array<string>,
  "wa_addressable": boolean,
  "wa_eligibility": number,
  "has_anonymous_profile_picture": boolean,
  "is_supervision_features_enabled": boolean,
  "all_media_count": number,
  "liked_clips_count": number,
  "fbid_v2": string,
  "interop_messaging_user_fbid": string,
  "is_using_unified_inbox_for_direct": boolean,
  "biz_user_inbox_state": number,
  "show_insights_terms": boolean,
  "nametag": { "mode": number, "gradient": number, "emoji": string, "selfie_sticker": number },
  "allowed_commenter_type": string,
  "has_placed_orders": boolean,
  "reel_auto_archive": string,
  "total_igtv_videos": number,
  "can_boost_post": boolean,
  "can_see_organic_insights": boolean,
  "is_business": boolean,
  "professional_conversion_suggested_account_type": number,
  "account_type": number,
  "is_category_tappable": boolean,
  "is_call_to_action_enabled": null,
  "allow_contacts_sync": boolean,
  "phone_number": string
}